from gui.widgets.actions.click_action_widget import ClickActionWidget
from gui.widgets.actions.wait_action_widget import WaitActionWidget
from gui.widgets.actions.if_action_widget import IfActionWidget
from gui.widgets.actions.search_for_if_action_widget import SearchForIfActionWidget